name: Check if plates are in stock
on:
  schedule:
    - cron: '*/5 * * * *'  # every five minutes
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
